version: '3'

networks: 
  nginx-php-mysql8-node: 

services: 
   
   #nginx 
  nginx-service:
      image: nginx:stable-alpine
      container_name: nginx-container
      ports: 
        - "8080:80"
      volumes: 
        - ./app/app:/var/www/app/app
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on: 
        - php-service
        - mysql8-service
      networks: 
        - nginx-php-mysql8-node
   #php
  php-service:
      build:
        context: .
        dockerfile: ./php/Dockerfile
      container_name: php74-container
      ports: 
        - "8000:8000"
      volumes: 
        - ./app/app:/var/www/app/app
      networks: 
        - nginx-php-mysql8-node

   #mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports: 
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql 
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # container always restarts.
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    networks: 
      - nginx-php-mysql8-node
   #node 
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./app-front
      dockerfile: ../vue/Dockerfile
    volumes:
      - "./app-front:/app"
      - "/app/node_modules"
    networks: 
        - nginx-php-mysql8-node  
    ports:
      - "8081:8081"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn start"
  
  maildev:
    image: maildev/maildev
    container_name: maildev_container
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports: 
      - "8082:80"
    networks: 
      - nginx-php-mysql8-node

      
